project:
  type: website
  output-dir: _site
  execute-dir: project

website:
  title: "Notes on Active Fuel"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
