---
title: "Calibration of Magnetic Sucseptibility Simulations"
date: 2026-08-09
author: "Antonio Ortiz-Ambriz"
---

# Introduction 

I'm trying to use LAMMPS to simulate the dynamics of superparamagnetic particles. In the experiments, the particles have a dipole moment given by:
$$\vec{m} = \frac{V\chi \vec{B}}{\mu_0}$$
where $V$ is the particle volume, $\chi$ is the magnetic susceptibility, $\vec{B}$ is the magnetic field, and $\mu_0$ is the magnetic constant. 
This note, along with the script [scripts/s0_test.lmpin], describe how to ensure that the dipole moments in LAMMPS have the correct magnitude in *micro* units. 

The LAMMPS script is run by the following cell: 
```{python}
! python3 run_sim.py \
  --script scripts/s0_test.lmpin \
  --data-dir data/ \
  --run-id 2026-08-08_Test_MagneticField \
  --notebook notebooks/2026-08-08_Test_MagneticField.qmd \
  --params

```

This script runs a simulation that consists of two particles, one fixed and the other moving. If the moment is calculated properly, that script should produce a force in on the moving particle, whose magnitude goes as the magnetic dipole force. 
$$F = \frac{3\mu_0}{4 \pi r^4} m^2$$
The force reported in the data is in pN.

To calculate the magnitude of the dipole moment, we can use the following code snippet:
```{.LAMMPS}

## magnetic dipole prefactor
variable radius equal 1.4
variable mu0 equal 4*PI*1e-10 
variable c equal 2.99792e8
variable chi equal 0.4
variable V equal 4/3*PI*v_radius^3
variable pref equal v_V * v_chi / v_mu0 / v_c

## Bmag can be made dynamic
variable Bmag equal 1e-6 # pg/us/pC

## the prefator is evaluated using ${} to ensure preeval.
variable dipole atom ${pref} * v_Bmag

```
To ensure consistent units, everything should be in pN, $\mu$m, $\mu$s, and pC, as desribed in (units)[https://docs.lammps.org/units.html]

The following python chunk reads the data:
```{python}
#| label: load-data
#| echo: true

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ovito.io import import_file

pipeline = import_file("data/2026-08-08_Test_MagneticField/test.lammpstrj")

# Iterate through all timesteps

trj = []
for frame in range(pipeline.num_frames):
    data = pipeline.compute(frame)

    # Access global properties
    timestep = data.attributes.get("Timestep", frame)
    cell = data.cell # Simulation box matrices

    # Access atom-wise properties as NumPy arrays
    atom_ids = data.particles.identifiers.array
    positions = data.particles.positions.array
    forces = data.particles["Force"].array

    trj.append(
      pd.DataFrame(
        {
          'step': timestep,
          'ids': atom_ids,
          'x': positions[:, 0],
          'y': positions[:, 1],
          'z': positions[:, 2],
          'fx': forces[:, 0],
          'fy': forces[:, 1],
          'fz': forces[:, 2],

        }))

trj = pd.concat(trj)
trj = (
  trj
  .set_index(["ids","step"])
  .sort_index()
)

```

### LAMMPS calulated force vs distance

```{python}
#| label: plot-force
#| caption: "Force vs distance calculated by LAMMPS compared to analytical calculation"
#| echo: true

import pint as pt
ureg = pt.UnitRegistry()

mu0 = 4*np.pi*1e-7 * ureg("N / A**2")

r = 1.4*ureg.um
V = 4/3 * np.pi * r**3
B = 1*ureg("mT")
chi = 0.4
m = (V*B*chi/mu0)

pf = 3 * mu0 / (4 * np.pi) * m**2

plt.figure(dpi=150, figsize=[3,2])

fx = pf.to("pg * um**5 / us**2").magnitude/(trj.loc[2].x)**4 
plt.plot(trj.loc[2].x, trj.loc[2].fx, '+-')
plt.plot(trj.loc[2].x, fx)
plt.xlabel(r"distance $\mu{}$m")
plt.ylabel(r"force pN")

```
